[versions]
agp = "8.5.1"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
ssp = "1.1.1"
sdp = "1.1.1"
retrofit = "2.11.0"
viewmodel = "2.8.4"
coroutines = "1.3.9"
androidchart = "v3.1.0"
glide = "4.16.0"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ssp = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "ssp" }
sdp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdp" }
androidchart = {group = "com.github.PhilJay", name  = "MPAndroidChart", version.ref = "androidchart"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel" }
livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "viewmodel" }
glide  = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
coroutines = {group = "org.jetbrains.kotlinx", name= "kotlinx-coroutines-android", version.ref = "coroutines"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

